# Generated by Django 4.2.7 on 2023-11-08 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("SIP", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unofficial",
            name="date_modified",
        ),
        migrations.AddField(
            model_name="unofficial",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="official",
            name="date_modified",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
