# Generated by Django 4.2.7 on 2023-11-10 20:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("SIP", "0002_remove_unofficial_date_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alternate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cocktail_tag",
                    models.CharField(
                        choices=[("o", "Official"), ("u", "Unofficial")], max_length=1
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=255, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("glass", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("ingredients", models.JSONField(default=dict)),
                ("image", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "image_source",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "image_attribution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_modified",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Official",
        ),
        migrations.DeleteModel(
            name="Unofficial",
        ),
        migrations.RemoveField(
            model_name="review",
            name="id_drink",
        ),
        migrations.RemoveField(
            model_name="review",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="star",
            name="id_drink",
        ),
        migrations.RemoveField(
            model_name="star",
            name="tag",
        ),
        migrations.AddField(
            model_name="star",
            name="rated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name="review",
            table=None,
        ),
        migrations.AlterModelTable(
            name="star",
            table=None,
        ),
        migrations.AddField(
            model_name="review",
            name="cocktail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SIP.cocktail",
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="cocktail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SIP.cocktail",
            ),
        ),
    ]
