# Generated by Django 4.2.7 on 2023-11-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("SIP", "0003_cocktail_delete_official_delete_unofficial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="tags",
        ),
        migrations.CreateModel(
            name="CocktailIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cocktail",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SIP.cocktail",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SIP.ingredient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, through="SIP.CocktailIngredient", to="SIP.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="cocktail",
            name="tags",
            field=models.ManyToManyField(blank=True, to="SIP.tag"),
        ),
    ]
