# Generated by Django 4.2.6 on 2023-11-13 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIP', '0004_ingredient_tag_remove_cocktail_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
