# Generated by Django 4.2.6 on 2023-11-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIP', '0005_alter_star_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_image/')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user_uploaded_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIP.useruploadedimage'),
        ),
    ]
