# Generated by Django 4.2.7 on 2023-11-20 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SIP", "0006_player"),
        ("SIP", "0008_alter_cocktail_user_uploaded_image"),
    ]

    operations = []
