# Generated by Django 4.2.7 on 2023-11-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIP', '0012_favouritecocktail_favouriteingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='favouriteingredient',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavouriteCocktail',
        ),
        migrations.DeleteModel(
            name='FavouriteIngredient',
        ),
    ]
