name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: sipdb
          POSTGRES_USER: sip
          POSTGRES_PASSWORD: sip
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set env
      run: |
        echo "DATABASE_URL=postgres://sip:sip@localhost:5432/sipdb" >> $GITHUB_ENV
        cp test.env .env
    - name: Run Tests
      run: |
        python manage.py test
